##################### AUTH

### create new user
POST http://localhost:3000/api/db/users/create_user
Content-Type: application/json

{
    "email": "test",
    "password": "test",
    "name" : "testAcc"
}

### login
POST http://localhost:3000/api/db/users/login
Content-Type: application/json

{
    "email": "test",
    "password": "test"
}


### logout
POST http://localhost:3000/api/db/users/logout

### refresh token
GET http://localhost:3000/api/db/users/refresh-token

### check token
GET http://localhost:3000/api/db/users/check-token
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

###################### NOTES

### create new note
POST http://localhost:3000/api/db/notes/create_note
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc


### get all notes info PASS
GET http://localhost:3000/api/db/notes/get_all_notes_info
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

### get note content by id 
GET http://localhost:3000/api/db/notes/get_note_content
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId": 1
}

### update note content by id 
PUT http://localhost:3000/api/db/notes/edit_content
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 1,
    "content" : "hidup jokowi"
}

### update note title by id 
PUT http://localhost:3000/api/db/notes/edit_title
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 1,
    "title" : "konze"
}

### set favorite
PUT http://localhost:3000/api/db/notes/set_favorite
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 1,
    "isFavorite": 1
}

### set archive PASS
PUT http://localhost:3000/api/db/notes/set_archive
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 1,
    "isArchive": 1
}

### set trash PASS
PUT http://localhost:3000/api/db/notes/set_trash
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 1,
    "isTrash": 1
}

### set note metadata by id
PUT http://localhost:3000/api/db/notes/edit_note_metadata
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 1,
    "title": "make apa ni orang? nyabukah?",
    "isFavorite": 1,
    "isArchive": 1,
    "isTrash": 1
}

### delete note PASSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
DELETE http://localhost:3000/api/db/notes/delete_note
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJlbWFpbCI6InRlc3QiLCJpYXQiOjE3NTkxMzgyMDUsImV4cCI6MTc1OTE0MDAwNX0.LqeFWJSUO2zKyad7A19ACYt_8I2LxXQsqRtv62wkXAc

{
    "noteId" : 2
}

