### login



### send email 
POST http://localhost:3000/api/db/users/send-reset-password-email
Content-Type: application/json

{
    "email": "kingahmadilyas05@gmail.com"
}

### reset password
POST http://localhost:3000/api/db/users/reset-password
Content-Type: application/json
Authorization: Bearer c6fd7c8082b693664dcc1f100cd67b4e300580a257a140aca58ce51376302aae

{
    "password": "konz123"
}