POST http://localhost:3000/api/db/users/login
Content-Type: application/json

{
    "email": "kingahmadilyas010@gmail.com",
    "password": "jawirgoreng"
}
###

POST http://localhost:3000/api/db/users/create_user
Content-Type: application/json

{
    "email": "kingahmadilyas010@gmail.com",
    "password": "jawirgoreng",
    "name" : "kingahmadilyas10"
}

###
POST http://localhost:3000/api/db/users/logout

###
GET http://localhost:3000/api/db/users/refresh-token

